from google.genai import types

# ...

root_agent = Agent(
    model='gemini-flash-latest',
    # ...
    generate_content_config=types.GenerateContentConfig(
        # ...
        http_options=types.HttpOptions(
            # ...
            retry_options=types.HttpRetryOptions(initial_delay=1, attempts=2),
            # ...
        ),
        # ...
    ),
)