package com.google.adk.kt.examples.agents.llmagent

import com.google.adk.kt.agents.LlmAgent
import com.google.adk.kt.agents.Instruction
import com.google.adk.kt.models.GeminiModel
import com.google.adk.kt.tools.AdkTool
import com.google.adk.kt.tools.AdkParam
import com.google.adk.kt.runners.InMemoryRunner
import com.google.adk.kt.sessions.InMemorySessionService
import com.google.adk.kt.types.Content
import com.google.adk.kt.types.Part
import com.google.adk.kt.types.GenerateContentConfig
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.runBlocking

// [START tool_definition]
class CapitalService {
    @AdkTool(description = "Retrieves the capital city for a given country.")
    fun getCapitalCity(@AdkParam("The country to get capital for.") country: String): String {
        val capitals = mapOf("france" to "Paris", "japan" to "Tokyo", "canada" to "Ottawa")
        return capitals[country.lowercase()] ?: "Sorry, I don't know the capital of $country."
    }
}
// [END tool_definition]

fun main() = runBlocking {
    val capitalService = CapitalService()
    
    // [START identity]
    val capitalAgent = LlmAgent(
        name = "capital_agent",
        model = GeminiModel("gemini-1.5-flash"),
        description = "Answers user questions about the capital city of a given country."
    )
    // [END identity]

    // [START instruction]
    val instructedAgent = LlmAgent(
        name = "capital_agent",
        model = GeminiModel("gemini-1.5-flash"),
        instruction = Instruction("""
            You are an agent that provides the capital city of a country.
            When a user asks for the capital of a country:
            1. Identify the country name from the user's query.
            2. Use the `getCapitalCity` tool to find the capital.
            3. Respond clearly to the user, stating the capital city.
            Example Query: "What's the capital of {country}?"
            Example Response: "The capital of France is Paris."
        """.trimIndent())
    )
    // [END instruction]

    // [START tool_usage]
    // Note: adkTools() is generated by KSP for classes containing @AdkTool annotated functions.
    // In a real project, you would need to set up the ADK KSP processor.
    // val agentWithTools = LlmAgent(
    //     name = "capital_agent",
    //     model = GeminiModel("gemini-1.5-flash"),
    //     tools = capitalService.adkTools() 
    // )
    // [END tool_usage]

    // [START gen_config]
    val agentWithConfig = LlmAgent(
        name = "capital_agent",
        model = GeminiModel("gemini-1.5-flash"),
        generateContentConfig = GenerateContentConfig(
            temperature = 0.2f,
            maxOutputTokens = 250
        )
    )
    // [END gen_config]

    // [START full_example]
    val finalAgent = LlmAgent(
        name = "capital_agent",
        model = GeminiModel("gemini-1.5-flash"),
        description = "Answers user questions about the capital city of a given country.",
        instruction = Instruction("You are an agent that provides the capital city of a country...")
        // tools = capitalService.adkTools() // Assuming tools are added
    )

    val sessionService = InMemorySessionService()
    val runner = InMemoryRunner(finalAgent, "capital_app", sessionService)
    
    val userMessage = Content(parts = listOf(Part(text = "What is the capital of France?")))
    
    // Use runAsync to get a Flow of events
    runner.runAsync(userId = "user123", sessionId = "session456", newMessage = userMessage).collect { event ->
        if (event.isFinalResponse && event.content != null) {
            println(event.content!!.parts[0].text)
        }
    }
    // [END full_example]
}
