name: Check Docs Health

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run health check script
        id: health_check
        continue-on-error: true
        run: python scripts/check_docs_health.py

      - name: Check for changes
        id: git_status
        run: |
          if git diff --quiet -- docs_health_report.md; then
            echo "No changes to report."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Health report or badge has changed."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with changes
        if: steps.git_status.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="docs-health/update-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git add docs_health_report.md
          git commit -m "docs: Update health report"
          git push origin $BRANCH_NAME
          gh pr create \
            --base "main" \
            --head "$BRANCH_NAME" \
            --title "docs: Update health report (${{ github.run_id }})" \
            --body "Automated documentation health report update. Please review and merge."
